server:
  port: 8081

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_driver?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 600MB
      max-request-size: 1024MB
logging:
  config: classpath:log4j2.yml
